services:
  postgres:
    image: postgres:17-alpine
    container_name: ghost-postgres
    environment:
      POSTGRES_USER: ghost
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ghost_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
